### ISSUE TITLE
Fixing date issue of blog post

### ISSUE THREAD

**Issue by MaxKuck** [deora-earth/website#8]
Wrong date of the [volt QV blog post](https://www.deora.earth/post/volt-party-uses-quadratic-voting-on-the-blockchain)
- correct date: September 10, 2019

![image](https://user-images.githubusercontent.com/45236782/67226613-a6c6c800-f435-11e9-8dda-6db466b4fafd.png)

**Comment by simonweniger** [comment]
done - 22.10
